spring:
  shardingsphere:
#    #内存模式
#    mode:
#      type: Memory
    #   数据源配置
    datasource:
      names: sharding-0,sharding-1
      sharding-0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: "com.mysql.cj.jdbc.Driver"
        url: "jdbc:mysql://localhost:3306/sharding-0?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8"
        username: root
        password: 123456
      sharding-1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: "com.mysql.cj.jdbc.Driver"
        url: "jdbc:mysql://localhost:3306/sharding-1?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8"
        username: root
        password: 123456
#   标准分片表配置
    rules:
      sharding:
        # 分片算法配置
        sharding-algorithms:
          database-inline:
            type: INLINE
            props:
              algorithm-expression: sharding$->{user_id % 2}
          alg_inline_order_id:
            type: INLINE
            props:
              algorithm-expression: t_order$->{order_id % 2}
        # 数据分片规则配置
        tables:
          t_user:
            # 水平分库，不分表
            actual-data-notes: sharding$->{0..1}.t_user
            # 分库策略
            database-strategy:
              # 单分片键的标准分片
              standard:
                # 分片列名称
                sharding-column: user_id
                #  分片策略
                sharding-algorithm-name: database-inline
            # 分布式序列策略
            key-generate-strategy:
              # 自增列名（自增主键）
              column: user_id
              # 自增算法
              key-generator-name: snowflake
          # 逻辑表名称
          t_order:
            # 水平分库且分表,实际表名称
            actual-data-notes: sharding$->{0..1}.t_order$->{0..1}
            # 分库策略
            database-strategy:
              # 单分片键的标准分片
              standard:
                # 分片列名称
                sharding-column: user_id
                #  分片策略
                sharding-algorithm-name: database-inline
            # 分表策略
            table-strategy:
              standard:
                sharding-column: order_id
                sharding-algorithm-name: alg_inline_order_id
            # 分布式序列策略
            key-generate-strategy:
              # 自增列名（自增主键）
              column: order_id
              # 自增算法
              key-generator-name: snowflake
        key-generators:
          snowflake:
            type: SNOWFLAKE
    props:
      sql-show: true
  jpa:
    properties:
      hibernate:
        show_sql: false
        ddl-auto: update


























#            # 分片审计策略
#            audit-strategy:
#              # 分片审计算法名称
#              auditor-names:
#                - sharding_key_required_auditor
#              # 是否禁用分片审计hint
#              allowHintDisable: true
#        # 自动分片表规则配置
#        auto-tables:
#          # 逻辑表名称
#          t_order: